### ISSUE TITLE
Remove `gnsst`, add `loct`.

### ISSUE THREAD

**Issue by coderbyheart** [NordicSemiconductor/asset-tracker-cloud-docs#568]
The configuration setting [is changed](https://github.com/nrfconnect/sdk-nrf/pull/8631) to a more general *location timeout* setting called `loct`. It configures the time the device can take to acquire any location information, using GNSS, and fall back to querying neighboring cells and WiFi cells.

The default value should be 300 seconds and generally be fairly large, otherwise fallback to cellular will never occur if GNSS fix is not acquired.

## Tasks

- [x] AWS firmware: https://github.com/NordicSemiconductor/asset-tracker-cloud-firmware-aws/issues/186
- [x] AWS Web App: https://github.com/NordicSemiconductor/asset-tracker-cloud-app-aws-js/issues/399
- [x] AWS backend https://github.com/NordicSemiconductor/asset-tracker-cloud-aws-js/issues/1226
- [x] Azure firmware: [56ef4f7b1052febbb90f5a9aa9c20bbffe451a8c](https://github.com/NordicSemiconductor/asset-tracker-cloud-firmware-azure/commit/56ef4f7b1052febbb90f5a9aa9c20bbffe451a8c)
- [ ] Azure backend: https://github.com/NordicSemiconductor/asset-tracker-cloud-azure-js/issues/561
- [ ] Azure Web App: https://github.com/NordicSemiconductor/asset-tracker-cloud-app-js/issues/556

**Comment by trantanen** [comment]
When is this expected to be implemented into the cloud?

**Comment by coderbyheart** [comment]
Once it lands in nRF Connect SDK main for the following release, probably 2.2.0.

**Comment by trantanen** [comment]
PR https://github.com/nrfconnect/sdk-nrf/pull/8631 has been merged so I guess this change could be done now.
