### ISSUE TITLE
Document how to customize the nRF Asset Tracker

### ISSUE THREAD

**Issue by coderbyheart** [NordicSemiconductor/asset-tracker-cloud-docs#65]
Document how users can customize the nRF Asset Tracker for the needs of their product.

I will show in the guide how to enable the display of a cat's *heartrate*: the tracker will constantly measure the heart rate of the cat and record it in a configurable interval and send it as a batch message when the device connects.

This will also show how to fork the project into the customers GitHub organization, using @acme-cat-tracker as the example organization.

- [x] ~~define a feature for the AWS solutions~~ (this is more involved, and technically not needed because the backend is data agnostic)
- [x] make the simulator standalone: https://github.com/NordicSemiconductor/asset-tracker-cloud-device-simulator-aws-js
- [x] use the standalone simulator in nRF Asset Tracker for AWS
  - https://github.com/NordicSemiconductor/asset-tracker-cloud-aws-js/pull/170
- [x] add the sensor to the simulator
- [x] add a chart to the web app
- [x] ~~add a new configuration setting for the sample rate~~ (needs to happen on the firmware side mostly, so left out for now)
